# Generated by Django 3.2.7 on 2024-01-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0002_staff_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
    ]
