# Generated by Django 3.2.7 on 2024-01-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0005_auto_20240119_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('staff_id', models.CharField(max_length=150)),
            ],
        ),
    ]
