# Generated by Django 3.2.7 on 2024-01-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0006_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='items_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=150)),
                ('subcat_id', models.CharField(max_length=150)),
                ('item_name', models.CharField(max_length=150)),
                ('item_desc', models.CharField(max_length=150)),
                ('item_price', models.CharField(max_length=150)),
                ('item_status', models.CharField(max_length=150)),
                ('item_brand', models.CharField(max_length=150)),
                ('item_image', models.FileField(max_length=150, upload_to='')),
            ],
        ),
    ]
