# Generated by Django 3.2.7 on 2024-02-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0007_items_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=150)),
                ('vendor_id', models.CharField(max_length=150)),
                ('pur_date', models.CharField(max_length=150)),
                ('pur_tot_amt', models.CharField(max_length=150)),
            ],
        ),
    ]
