# Generated by Django 3.2.7 on 2024-02-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0008_purchase_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_master_id', models.CharField(max_length=150)),
                ('item_id', models.CharField(max_length=150)),
                ('pur_qty', models.CharField(max_length=150)),
                ('unit_price', models.CharField(max_length=150)),
                ('stock', models.CharField(max_length=150)),
                ('sell_price', models.CharField(max_length=150)),
                ('tot_price', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='items_tbl',
            name='item_stock',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
