# Generated by Django 3.2.7 on 2024-02-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0009_auto_20240201_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_master_id', models.CharField(max_length=150)),
                ('item_id', models.CharField(max_length=150)),
                ('cart_qty', models.CharField(max_length=150)),
                ('cart_price', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='cart_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customert_id', models.CharField(max_length=150)),
                ('cart_tot_amt', models.CharField(max_length=150)),
                ('cart_status', models.CharField(max_length=150)),
            ],
        ),
    ]
