# Generated by Django 3.2.7 on 2024-02-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0010_cart_child_cart_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_tbl',
            name='item_stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
