# Generated by Django 3.2.7 on 2024-02-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0011_alter_items_tbl_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_child',
            name='cart_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart_master',
            name='cart_tot_amt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='items_tbl',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
