# Generated by Django 3.2.7 on 2024-02-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0012_auto_20240206_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_child',
            name='cart_qty',
            field=models.PositiveIntegerField(),
        ),
    ]
