# Generated by Django 3.2.7 on 2024-02-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0013_alter_cart_child_cart_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=150)),
                ('card_no', models.CharField(max_length=150)),
                ('exp_date', models.CharField(max_length=150)),
                ('cvv', models.CharField(max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationary.customer_reg')),
            ],
        ),
    ]
