# Generated by Django 3.2.7 on 2024-02-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0015_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=150)),
                ('co_name', models.CharField(max_length=150)),
                ('co_city', models.CharField(max_length=150)),
                ('co_dist', models.CharField(max_length=150)),
                ('co_pin', models.CharField(max_length=150)),
                ('co_street', models.CharField(max_length=150)),
                ('co_phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('co_status', models.CharField(max_length=150)),
            ],
        ),
    ]
