# Generated by Django 3.2.7 on 2024-02-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0016_tbl_courier'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cassign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.CharField(max_length=150)),
                ('cassign_date', models.CharField(max_length=150)),
                ('cart_master_id', models.CharField(max_length=150)),
            ],
        ),
    ]
