# Generated by Django 3.2.7 on 2024-02-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0017_tbl_cassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='status',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
