# Generated by Django 3.2.7 on 2024-02-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0018_tbl_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cassign',
            name='status',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
