# Generated by Django 3.2.7 on 2024-02-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0020_tbl_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('user_type', models.CharField(max_length=150)),
            ],
        ),
    ]
